### ISSUE TITLE
Add support for Svelte 5

### ISSUE THREAD

**Issue by xelius** [nubolab-ffwd/svelte-fluent#1185]
Svelte 5 has reached RC status.
Thanks!

**Comment by sfriedel** [comment]
Hi @xelius, Svelte 5 support is in the works. Still need to update everything to the latest RC and work out some issues but the new version should be ready Soon™.

**Comment by sfriedel** [comment]
A preview version of svelte-fluent 1.0.0 with svelte 5 support is now available on the [next](https://github.com/nubolab-ffwd/svelte-fluent/tree/next) branch. The README on that branch has instructions how to install it and the link to the preview documentation site.
