### ISSUE TITLE
`TypeError: Cannot read properties of undefined (reading '$$')`

### ISSUE THREAD

**Issue by macabeus** [nubolab-ffwd/svelte-fluent#686]
Hello, thanks for the package!
I'm trying to use this package on my personal project built with SvelteKit, but I have the following error:
```
index.mjs:307 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$$')
    at init (index.mjs:307:50)
```

It refers to the following line:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/9501115/219987728-1b9adb4f-24fa-404a-8d13-534d0354b387.png">

I tried to fix it by adding a parent to `FluentProvider`, but it didn't fix that.

Commit with the changes: https://github.com/gambiconf/gambiconf.github.io/commit/a4f61cbbb4d9077204466037cdd2ccef22c4df93
You can easily follow the project readme to reproduce it.

**Comment by sfriedel** [comment]
Thank you for reporting this issue @macabeus. I haven't seen this one before, but it reminds me of problems I had in the past where for some reason multiple separate instances of `svelte` got included in the bundle which lead to broken behavior of svelte contexts.

I'll try to give it a check later.

**Comment by sfriedel** [comment]
@macabeus it appears the issue is `vite@4.1.2` and to fix the problem you need to update to `vite@4.1.3`.

You can simply run

```
npm i -D vite@4.1.3
```

I'm still not sure what exactly the problem was with `vite@4.1.2`. I didn't really find anything that seemed related in their changelog.
