### ISSUE TITLE
Including non-printable UNICODE characters⁨⁩ `U+2068` and `U+2069` before/after a placement

### ISSUE THREAD

**Issue by macabeus** [nubolab-ffwd/svelte-fluent#718]
I don't know if it's expected, but I noticed that when using a placement, this library includes the UNICODE characters [`U+2068`](https://www.compart.com/en/unicode/U+2068) and [`U+2069`](https://www.compart.com/en/unicode/U+2069).

You can reproduce it by doing the following:
```ftl
message = -{ $foo }-
```
```svelte
<script>
  import { Localized } from "@nubolab-ffwd/svelte-fluent"
</script>

<Localized id="message" args={{ foo: 'value' }} let:text>
  {console.log(text)}
</Localized>
```

Then, copy the console output on VS Code:

<img width="185" alt="image" src="https://user-images.githubusercontent.com/9501115/222996899-c8bb4ad5-ce48-4265-8187-67d9843f54d0.png">

It usually isn't a big deal, but if you are using the output on the `img` `src` attribute or making a string comparison, it can be bad.

**Comment by sfriedel** [comment]
@macabeus as far as I can tell this is an intentional behavior in fluent that is documented here: https://github.com/projectfluent/fluent.js/wiki/Unicode-Isolation

You can turn this behavior off by setting the `useIsolating: false` option when constructing the `FluentBundle` like this:

```js
new FluentBundle(locale, {useIsolating: false});
```
