### ISSUE TITLE
Breaks with Svelte Devtools

### ISSUE THREAD

**Issue by ShittyKopper** [nubolab-ffwd/svelte-fluent#828]
(Or at least, the stack trace blames this)

With [the dev tools](https://github.com/sveltejs/svelte-devtools/) closed. everything seems fine. but after opening it and clicking to enable. this stack trace gets printed every reload. and overlays are broken (regular translations seem to work fine) until you close the tab and open another one.

[console-export-2023-6-14_15-48-52.txt](https://github.com/nubolab-ffwd/svelte-fluent/files/11745867/console-export-2023-6-14_15-48-52.txt)

Dependencies list pruned only to ones I believe are relevant:

```json
	"devDependencies": {
		"@nubolab-ffwd/svelte-fluent": "^0.6.1",
		"@sveltejs/adapter-node": "^1.2.4",
		"@sveltejs/adapter-static": "^2.0.2",
		"@sveltejs/kit": "^1.5.0",
		"svelte": "^3.54.0",
		"svelte-check": "^3.0.1",
		"vite": "^4.3.0"
	},
	"dependencies": {
		"@fluent/bundle": "^0.18.0",
		"@fluent/langneg": "^0.7.0",
		"accept-language-parser": "^1.5.0",
		"jsdom": "^22.1.0",
	}
```

plus Svelte DevTools 1.3.0

**Comment by sfriedel** [comment]
@ShittyKopper The exception comes from an unfortunate incompatibility between the way `svelte-devtools` accesses private component state and [cached-iterable](https://www.npmjs.com/package/cached-iterable) which `svelte-fluent` uses internally.

I have a mitigation for the problem in place now and will publish an new version later.
